-- MySQL Script generated by MySQL Workbench
-- Tue Feb 11 17:40:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gerencia_lbff
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerencia_lbff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerencia_lbff` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `gerencia_lbff` ;

-- -----------------------------------------------------
-- Table `gerencia_lbff`.`adiministradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerencia_lbff`.`adiministradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `login` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerencia_lbff`.`campoenato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerencia_lbff`.`campeonato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `pontuacao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
